const help = {
    usage: "makegraph [weight] [semestersoffered] -hdgcr -ext -dpt [department] -coursecode [coursecode] -limit [limitnumber] -pdf [pdfName] -prq [prereq] -title [keyword] -level [level] -path [coursecode] -program [degreeprogram] -major -minor -AOC/-AOE",
    commands: [
        "-h",
        "-d",
        "-g",
        "-c",
        "-r",
        "-ext",
        "-dpt",
        "-pdf",
        "-prq",
        "-path",
        "-coursecode",
        "-limit",
        "-title",
        "-level",
        "-program",
        "-major",
        "-minor",
        "-AOE / -AOC",
    ],
    cmddescriptions: [
        "Brings up the help menu, listing command flags and query types",
        "Terminal mode: Graph results will display to the terminal instead of the PDF",
        "Includes graduate level courses",
        "Hide corequisite courses",
        "Show restricted courses",
        "Includes external courses outside of department courses",
        "Usage: -dpt [x] where x is either a 3 letter or 4 letter word ie: ENGG or CIS, will create graph with courses  where the department code matches x",
        "Usage: -pdf [x] where x is the name of the PDF file",
        "Usage: -prq [x] where x follows the format of `3 letters : 4 numbers` or `4 letters : 4 numbers` ie: CIS*1300 or PHYS*1130, creates graph with courses that use x as a prerequisite",
        "Usage: -path [x] where x follows the format of `3 letters : 4 numbers` or `4 letters : 4 numbers` ie: CIS*1300 or PHYS*1130, creates graph with courses that use x as a prerequisite as well as the courses that require x",
        "Usage: -coursecode [x] where x follows the format of `3 letters : 4 numbers` or `4 letters : 4 numbers` ie: CIS*1300 or PHYS*1130, creates graph with courses that require x",
        "Usage: -limit [x] where x is the number of courses to include",
        "Usage: -title [keyword], will search for all course titles containing keyword",
        "Usage: -level [x] where x is 4 digit number ending with 000 (ex: 1000, 2000, etc), will find all results with with course numbers that are the level of x",
        "Usage: -program [degreeprogram], Will generate a graph containing all courses and prerequisites belonging to the supplied degree program",
        "To be used with -program, -major will hide the graph generated from a program's major",
        "To be used with -program, minor will show a graph of all the courses related to the minor",
        "To be used with -program -AOE / -AOC will show a graph of all the courses required to complete the area of concentration/emphasis",
    ],
    querytypes: ["semester", "weight", "department", "coursecode", "limitnumber", "pdfName", "prerequisite", "major"],
    querydesc: [
        "This query will look for all courses offered in a given semester, [S, F, W] summer, fall, winter respectively.",
        "This query will look for all courses with a given credit weight. [0.25, 0.5, 0.75, 1.00]",
        "This query will look for all courses in a specific department code. ie: CIS will create a graph with the department code CIS",
        "This query is a combination of department and course number search. ie: key CIS*1300 will return only CIS*1300",
        "This query limits the number of courses that will be created for the graph",
        "This query creates the filename for the PDF (default is 'graph.pdf'). Must end with '.pdf'",
        "This query will create a graph based on a specific prerequisite. \n Accepted are: \n 3 and 4 letter course codes (ie: CIS*1300 or PHYS*1010) \n 3 and 4 letter batchelor codes (BCOMP:SENG, BSC:ENV)",
        "This query will create a graph based on a specific major program's courses and prerequisites, ie: CS or PSYC",
    ],
};

export default help;
