name: CD/dogsbarking-setupUser

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-setupUser/**"
      - ".github/workflows/cd-dogsbarking-setupUser.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-setupUser
    secrets: inherit
