name: CD/dogsbarking-sendFeedback

on:
  push:
    branches:
      - dev
    paths:
      - "src/api/dogsbarking-sendFeedback/**"
      - ".github/workflows/cd-dogsbarking-sendFeedback.yml"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  FUNCTION_NAME: dogsbarking-sendFeedback

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./src/api/${{env.FUNCTION_NAME}}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FUNCTION_NAME: ${{ env.FUNCTION_NAME }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$FUNCTION_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$FUNCTION_NAME
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$FUNCTION_NAME"

      - name: Deploy function
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --image-uri ${{ steps.build-image.outputs.image }}

      - name: Configure function
        run: |
          aws lambda wait function-updated --function-name ${{ env.FUNCTION_NAME }}
          aws lambda update-function-configuration \
          --function-name ${{ env.FUNCTION_NAME }} \
          --timeout 600
