name: CD/dogsbarking-sendFeedback

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-sendFeedback/**"
      - ".github/workflows/cd-dogsbarking-sendFeedback.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-sendFeedback
