name: CD/dogsbarking-getUserDegreePlans

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-getUserDegreePlans/**"
      - ".github/workflows/cd-dogsbarking-getUserDegreePlans.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-getUserDegreePlans
    secrets: inherit
