name: CD/dogsbarking-getUser

on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/dogsbarking-getUser/**"
      - ".github/workflows/cd-dogsbarking-getUser.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-getUser
    secrets: inherit
