name: CD/dogsbarking-searchPrograms

on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/dogsbarking-searchPrograms/**"
      - ".github/workflows/cd-dogsbarking-searchPrograms.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-searchPrograms
    secrets: inherit
