name: CD/dogsbarking-executeProgramQuery

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-executeProgramQuery/**"
      - ".github/workflows/cd-dogsbarking-executeProgramQuery.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-executeProgramQuery
    secrets: inherit
