name: CD/dogsbarking-addSectionsToDegreePlanSemester

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-addSectionsToDegreePlanSemester/**"
      - ".github/workflows/cd-dogsbarking-addSectionsToDegreePlanSemester.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-addSectionsToDegreePlanSemester
    secrets: inherit
