name: CD/dogsbarking-updatePlannerSemester

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-updatePlannerSemester/**"
      - ".github/workflows/cd-dogsbarking-updatePlannerSemester.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-updatePlannerSemester
    secrets: inherit
