name: CD/dogsbarking-executeCourseQuery

on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/dogsbarking-executeCourseQuery/**"
      - ".github/workflows/cd-dogsbarking-executeCourseQuery.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-executeCourseQuery
    secrets: inherit
