name: CD/dogsbarking-removeCourseFromDegreePlanSemester

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-removeCourseFromDegreePlanSemester/**"
      - ".github/workflows/cd-dogsbarking-removeCourseFromDegreePlanSemester.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-removeCourseFromDegreePlanSemester
    secrets: inherit
