name: CD/dogsbarking-getDegreePlan

on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/dogsbarking-getDegreePlan/**"
      - ".github/workflows/cd-dogsbarking-getDegreePlan.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-getDegreePlan
    secrets: inherit
