name: CD/dogsbarking-getAllSchools

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-getAllSchools/**"
      - ".github/workflows/cd-dogsbarking-getAllSchools.yml"
      - ".github/workflows/cd-lambda-default.yml"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-getAllSchools
    secrets: inherit
