name: CD/dogsbarking-createDegreePlan

on:
  push:
    branches:
      - dev
    paths:
      - "apps/api/dogsbarking-createDegreePlan/**"
      - ".github/workflows/cd-dogsbarking-createDegreePlan.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-createDegreePlan
    secrets: inherit
