name: CD/dogsbarking-deleteDegreePlanSemester

on:
  push:
    branches:
      - dev
    paths:
      - "api/dogsbarking-deleteDegreePlanSemester/**"
      - ".github/workflows/cd-dogsbarking-deleteDegreePlanSemester.yml"
      - ".github/workflows/cd-lambda-default.yml"
      - "docker/api/Dockerfile"

jobs:
  deploy:
    name: Deploy Lambda
    uses: ./.github/workflows/cd-lambda-default.yml
    with:
      function-name: dogsbarking-deleteDegreePlanSemester
    secrets: inherit
